version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_practicum_intershop
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_practicum_intershop
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  intershop:
    build:
      context: .
      dockerfile: project/intershop/Dockerfile
    container_name: practicum_intershop_intershop
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - pay
      - redis
      - postgres
    volumes:
      - ./upload:/intershop/upload

  pay:
    env_file:
      - .env
    build:
      context: .
      dockerfile: project/pay/Dockerfile
    container_name: practicum_intershop_pay
    ports:
      - "8081:8081"

  keycloak:
    image: keycloak/keycloak:26.2.4
    container_name: keycloak_practicum_intershop
    env_file:
      - .env
    ports:
      - 8480:8080
      - 8454:5005
    volumes:
      - keycloak_data:/opt/keycloak/data/import
    command:
      - start-dev

volumes:
  postgres_data:
  redis_data:
  keycloak_data:
